---
 - name: initialize the cluster
   shell: kubeadm init --pod-network-cidr=10.244.0.0/16 
   
 - name: create .kube directory
   become: yes
   become_user: "{{ ansible_user }}"
   file:
     path: $HOME/.kube
     state: directory
     mode: 0755

 - name: copy admin.conf to user's kube config
   become: true
   copy:
     src: /etc/kubernetes/admin.conf
     dest: "/home/{{ansible_user}}/.kube/config"
     remote_src: yes
     owner: "{{ ansible_user }}"

 - name: change ownership
   ansible.builtin.file:
     path: /etc/kubernetes/admin.conf
     owner: "{{ ansible_user }}"
     group: "{{ ansible_user }}"
     mode: '0777'

 - name: install Pod network
   become: yes
   become_user: "{{ ansible_user}}"
   shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml



